server:
  base_url: http://localhost:5000
  timeout: 600
  max_workers: 48
# Benchmark parameters
benchmark:
  # Service functions to benchmark
  functions: 
    - create_environments_batch
    - reset_batch
    - step_batch
    - compute_reward_batch
    - get_system_prompts_batch
    - close_batch
  
  # Number of iterations for statistical significance
  iterations: 3
  
  # Number of steps to perform for each environment
  step_count: 5
  
  # Batch sizes to test
  batch_sizes: [8, 128]
  
  # Maximum number of parallel workers
  max_workers: 8
  
  # Directory to save benchmark results
  output_dir: "env_benchmark_results"

# Datasets to use for benchmarking
datasets:
  - name: detectagent-vision
    train_path: data/detectagent-vision-benchmark/train.parquet
    test_path: data/detectagent-vision-benchmark/test.parquet